---
# Restart of service status
# Use this task using below command
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags restserv
# Author: Hemant Gangwar

   - name: Restarting back |SYSTEMD| & |INITD| based services
     service:
       name: "{{ item }}"
       state: restarted
     with_items: "{{ mkt_application_service_list }}"
     when: mkt_application_service_list is defined
     tags: restserv

   - name: Starting back |SHELL| based applications
     shell: "{{ item }}"
     with_items: "{{ application_shell_restart_commands }}"
     when: application_shell_restart_commands is defined
     tags: restserv
