---
# Shutdown task, make sure to invoke it using appropriate tag
# Use this task using below command
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags shutdown
# Author: Hemant Gangwar

   - name: Bringing down |SYSTEMD| & |INITD| based services
     service:
       name: "{{ item }}"
       state: stopped
     with_items: "{{ mkt_application_service_list }}"
     when: mkt_application_service_list is defined
     tags: shutdown

   - name: Bringing down |SHELL| based applications
     shell: "{{ item }}"
     with_items: "{{ application_shell_stop_commands }}"
     when: application_shell_stop_commands is defined
     tags: shutdown
