---
# This playbook is learningtechnix.in proprietary for managing 
# application control for systemd and initd based services.
# Author: Hemant Gangwar
# v 1.0 Dated 05 November 2020
# Execute playbook with tags only
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags restserv
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags startup
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags shutdown
# ansible-playbook -i <inventory_name> generic_application_control.yml --tags verify

- name: Playbook for application control, make sure you are using tags 
  hosts: all
  gather_facts: yes
  tasks:
  - name: "[ ------------ | Shutdown PLAYBOOK | ---------------- ]"
    include_tasks: application-stop.yml
    tags: shutdown
    when: "'shutdown' in  ansible_run_tags"

  - name: "[ ------------ | Startup PLAYBOOK | ---------------- ]"
    include_tasks: application-start.yml
    tags: startup
    when: "'startup' in  ansible_run_tags"

  - name: "[ ------------ | Restart PLAYBOOK | ---------------- ]"
    include_tasks: application-restart.yml
    tags: restserv
    when: "'restserv' in  ansible_run_tags"

  - name: "[ ------------ | Verification PLAYBOOK | ---------------- ]"
    include_tasks: application-verify.yml
    tags: verify
    when: "'verify' in  ansible_run_tags"

